fix checks in pipelines that only do gets

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -57,18 +57,8 @@ elif [ -n "$repository_cert" ]; then
   cert="--cacert $working/security/repository.crt"
 fi
 
-# convert 1.0.0-20170328.031519-19 to 1.0.0-SNAPSHOT
-uniqueVersion=$(echo "$version" | grep -oE "[0-9]{8}\.[0-9]{6}-[0-9]{1,}" || true)
-if [ -n "$uniqueVersion" ]; then
-  version=$(echo ${version%-$uniqueVersion}-SNAPSHOT)
-fi
-
-if [[ "$version" = *-SNAPSHOT ]]; then
-  metadataUrl="$url/${groupId//.//}/$artifactId/$version/maven-metadata.xml"
-else
-  metadataUrl="$url/${groupId//.//}/$artifactId/maven-metadata.xml"
-fi
-
+#get artifact metadata
+metadataUrl="$url/${groupId//.//}/$artifactId/maven-metadata.xml"
 set +e
 metadata=$(curl --fail --silent --show-error $cert $auth $metadataUrl 2>&1)
 if [ $? -ne 0 ]; then
@@ -78,13 +68,53 @@ if [ $? -ne 0 ]; then
 fi
 set -e
 
+if [ -z $version ]; then
+  #get the version if it's null
+  version=$(echo $metadata | xmllint --xpath "/metadata/versioning/versions/version[1]/text()" - 2>/dev/null)
+else
+  # convert 1.0.0-20170328.031519-19 to 1.0.0-SNAPSHOT
+  uniqueVersion=$(echo "$version" | grep -oE "[0-9]{8}\.[0-9]{6}-[0-9]{1,}" || true)
+  if [ -n "$uniqueVersion" ]; then
+    version=$(echo ${version%-$uniqueVersion}-SNAPSHOT)
+  fi
+fi
+
 declare -a versions=( )
 if [[ "$version" = *-SNAPSHOT ]]; then
-  if [[ -z "$classifier" ]]; then
-    versions[1]=$(echo $metadata | xmllint --xpath "/metadata/versioning/snapshotVersions/snapshotVersion[extension='$packaging' and not(classifier)]/value/text()" - 2>/dev/null)
-  else
-    versions[1]=$(echo $metadata | xmllint --xpath "/metadata/versioning/snapshotVersions/snapshotVersion[extension='$packaging' and classifier='$classifier']/value/text()" - 2>/dev/null)
-  fi
+  declare -a snapshotVersions=( )
+
+  #get current and all new 'unique' snapshot versions from artifact metadata
+  itemsCount=$(echo $metadata | xmllint --xpath 'count(/metadata/versioning/versions/version)' - 2>/dev/null)
+  found=false
+  for (( i=1; i <= $itemsCount; i++ )); do
+    current=$(echo $metadata | xmllint --xpath "/metadata/versioning/versions/version[$i]/text()" - 2>/dev/null)
+    if [ "$found" = false ] && [ "$current" = "$version" ]; then
+      found=true
+    fi
+
+    if [ "$found" = true ]; then
+      snapshotVersions[$i]=$current
+    fi
+  done
+
+  #get latest snapshot version for each 'unique' version
+  for i in "${!snapshotVersions[@]}"; do
+    snapshotMetadataUrl="$url/${groupId//.//}/$artifactId/${snapshotVersions[$i]}/maven-metadata.xml"
+    set +e
+    snapshotMetadata=$(curl --fail --silent --show-error $cert $auth $snapshotMetadataUrl 2>&1)
+    if [ $? -ne 0 ]; then
+      printf '\e[91m[ERROR]\e[0m %s\n' "$snapshotMetadata"
+      printf '\e[91m[ERROR]\e[0m failed to download maven-metadata.xml from: %s\n' "$snapshotMetadataUrl"
+      exit 2
+    fi
+    set -e
+    if [[ -z "$classifier" ]]; then
+      versions[$i]=$(echo $snapshotMetadata | xmllint --xpath "/metadata/versioning/snapshotVersions/snapshotVersion[extension='$packaging' and not(classifier)]/value/text()" - 2>/dev/null)
+    else
+      versions[$i]=$(echo $snapshotMetadata | xmllint --xpath "/metadata/versioning/snapshotVersions/snapshotVersion[extension='$packaging' and classifier='$classifier']/value/text()" - 2>/dev/null)
+    fi
+  done
+
 elif [ "$version" = "latest" ] || [ -z "$version" ]; then
   versions[1]=$(echo $metadata | xmllint --xpath "/metadata/versioning/versions/version[last()]/text()" - 2>/dev/null)
 else
